// <auto-generated />
using System;
using ErenTravel3API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErenTravel3API.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20260124132621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ErenTravel3API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Emri");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ErenTravel3API.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Cmimi");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsAvailable");

                    b.Property<int>("Kohezgjatja")
                        .HasColumnType("int")
                        .HasColumnName("Kohezgjatja");

                    b.Property<string>("Paketa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Paketa");

                    b.Property<string>("Pershkrimi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Pershkrimi");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cmimi = 299m,
                            IsAvailable = true,
                            Kohezgjatja = 5,
                            Paketa = "Budapest – Hungari",
                            Pershkrimi = "Fluturim + Hotel • Nisja nga Tirana"
                        },
                        new
                        {
                            Id = 2,
                            Cmimi = 305m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Pragë – Çeki",
                            Pershkrimi = "Hotel 4★ • Vizita panoramike"
                        },
                        new
                        {
                            Id = 3,
                            Cmimi = 699m,
                            IsAvailable = true,
                            Kohezgjatja = 5,
                            Paketa = "Dubai – Emiratet",
                            Pershkrimi = "Guide • Hotel 4★ • Safari në shkretëtirë"
                        },
                        new
                        {
                            Id = 4,
                            Cmimi = 399m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Paris – Francë",
                            Pershkrimi = "Guidë • Hotel • Qyteti i dritave"
                        },
                        new
                        {
                            Id = 5,
                            Cmimi = 499m,
                            IsAvailable = true,
                            Kohezgjatja = 5,
                            Paketa = "DisneyLand Paris – Francë",
                            Pershkrimi = "Guide • Hotel 4★ • Argëtim familjar"
                        },
                        new
                        {
                            Id = 6,
                            Cmimi = 344m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Venecia, Verona – Itali",
                            Pershkrimi = "Guide • Hotel 4★ • Qytetet romantike"
                        },
                        new
                        {
                            Id = 7,
                            Cmimi = 99m,
                            IsAvailable = true,
                            Kohezgjatja = 2,
                            Paketa = "Firence – Itali",
                            Pershkrimi = "Hotel 3★ • Arti dhe kultura"
                        },
                        new
                        {
                            Id = 8,
                            Cmimi = 179m,
                            IsAvailable = true,
                            Kohezgjatja = 3,
                            Paketa = "Bruge – Belgjikë",
                            Pershkrimi = "Fluturim + Hotel + Mëngjes"
                        },
                        new
                        {
                            Id = 9,
                            Cmimi = 149m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Stockholm – Suedi",
                            Pershkrimi = "Fluturim + Hotel • Kryeqyteti skandinav"
                        },
                        new
                        {
                            Id = 10,
                            Cmimi = 419m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Strasburg - Francë • Zyrih - Zvicërr",
                            Pershkrimi = "Guide • Hotel 4★ • Dy vende"
                        },
                        new
                        {
                            Id = 11,
                            Cmimi = 699m,
                            IsAvailable = true,
                            Kohezgjatja = 7,
                            Paketa = "Arabi Saudite",
                            Pershkrimi = "Guide • Hotel 4★ • Eksplorim kulturor"
                        },
                        new
                        {
                            Id = 12,
                            Cmimi = 1199m,
                            IsAvailable = true,
                            Kohezgjatja = 6,
                            Paketa = "Jordani",
                            Pershkrimi = "Guide • Hotel 4★ • Petra dhe më shumë"
                        },
                        new
                        {
                            Id = 13,
                            Cmimi = 175m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Bukuresht – Rumani",
                            Pershkrimi = "Fluturim + Hotel 3★"
                        },
                        new
                        {
                            Id = 14,
                            Cmimi = 399m,
                            IsAvailable = true,
                            Kohezgjatja = 4,
                            Paketa = "Barcelonë – Spanjë",
                            Pershkrimi = "Fluturim + Hotel • Oferta fundviti"
                        },
                        new
                        {
                            Id = 15,
                            Cmimi = 135m,
                            IsAvailable = true,
                            Kohezgjatja = 3,
                            Paketa = "Alberobello – Itali",
                            Pershkrimi = "Fluturim + Hotel • Fshati karakteristik"
                        },
                        new
                        {
                            Id = 16,
                            Cmimi = 249m,
                            IsAvailable = true,
                            Kohezgjatja = 3,
                            Paketa = "Korçë – Shqipëri",
                            Pershkrimi = "Hotel Kocibelli • Viti i Ri tradicional"
                        });
                });

            modelBuilder.Entity("ErenTravel3API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Cmimi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataKthimit")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataKthimit");

                    b.Property<DateTime>("DataNisjes")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataNisjes");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsConfirmed");

                    b.Property<int>("NrDhomave")
                        .HasColumnType("int")
                        .HasColumnName("NrDhomave");

                    b.Property<int>("NrPersonave")
                        .HasColumnType("int")
                        .HasColumnName("NrPersonave");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PackageId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ErenTravel3API.Models.Reservation", b =>
                {
                    b.HasOne("ErenTravel3API.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErenTravel3API.Models.Package", "Package")
                        .WithMany("Reservations")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ErenTravel3API.Models.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ErenTravel3API.Models.Package", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
